# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KDTWvry68c9SDPvoIGqL7mLLZcWdwUb
"""

from pathlib import Path
import os

# Project root = parent of src/
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Data dirs
DATA_DIR = PROJECT_ROOT / "data"
DATA_RAW_DIR = DATA_DIR / "raw"
CHROMA_DIR = DATA_DIR / "chroma_db"

DATA_RAW_DIR.mkdir(parents=True, exist_ok=True)
CHROMA_DIR.mkdir(parents=True, exist_ok=True)

# Models
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
OPENAI_MODEL_NAME = os.getenv("OPENAI_MODEL_NAME", "gpt-4.1-mini")

# OpenAI key (read from env)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")