# -*- coding: utf-8 -*-
"""embeddings.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KDTWvry68c9SDPvoIGqL7mLLZcWdwUb
"""

from typing import List
from langchain_core.embeddings import Embeddings
from sentence_transformers import SentenceTransformer

class SBERTEmbeddings(Embeddings):
    """SentenceTransformer wrapper that matches LangChain's Embeddings API."""

    def __init__(self, model_name: str = "sentence-transformers/all-MiniLM-L6-v2"):
        self.model = SentenceTransformer(model_name)

    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        return self.model.encode(texts, show_progress_bar=False).tolist()

    def embed_query(self, text: str) -> List[float]:
        return self.model.encode([text], show_progress_bar=False)[0].tolist()