# -*- coding: utf-8 -*-
"""retriever.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KDTWvry68c9SDPvoIGqL7mLLZcWdwUb
"""

from langchain_community.vectorstores import Chroma

from src.config import CHROMA_DIR, EMBEDDING_MODEL_NAME
from src.rag.embeddings import SBERTEmbeddings


class UrbanRegulationsRetriever:
    def __init__(self, k: int = 5):
        self.k = k
        self._embedding = SBERTEmbeddings(EMBEDDING_MODEL_NAME)
        self._db = Chroma(
            persist_directory=str(CHROMA_DIR),
            embedding_function=self._embedding,
        )

    def retrieve(self, query: str):
        """Return top-k relevant LangChain Document objects."""
        return self._db.similarity_search(query, k=self.k)